### ISSUE TITLE
File Structure (Client) 

### ISSUE THREAD

**Issue by Fatmasiam** [FACG6/AMiDEAST#1]
* Client 
  * public/
      - index.html 
      - mainicon.icon
  * src/ 
    * Components/
       - Layout/
            - Mobile 
               - index.js
              - index.css
            - Desktop
                 - index.js
              - index.css
           * SideBar
              - index.js
              - index.css
          * HamburgerMenu
              - index.js
              - index.css
          * Footer
              - index.js
              - index.css
         * Header
            - index.js
            - index.css
       - Common/
         * Button 
            - index.js
            - index.css
         * Course
            - index.js
            - index.css
         * Label
            - index.js
            - index.css
         * DatePiker
            - index.js
            - index.css
         * Input
            - index.js
            - index.css
         * LinkList
            - index.js
            - index.css
         * Link
            - index.js
            - index.css
         * Table
            - index.js
            - index.css
         * PickDay
            - index.js
            - index.css
         * PickTime
            - index.js
            - index.css
         * Search
            - index.js
            - index.css
     - Contanier/
         * Auth/ 
           * login.js
           * login.css
         * Student/
           * Profile/
             * index.js
             * index.css
           * Course/
             * index.js
             * index.css
           * ApplyCourse/
             * index.js
             * index.css
           * index.js
        * Staff/
           * AddCourse/
             * index.js
             * index.css
           * ViewCourse/
             * index.js
             * index.css
           * EditStudent/
             * index.js
             * index.css
           * AddStudent/
             * index.js
             * index.css
           * ViewStudent/ 
             * index.js
             * index.css
           * index.js
    * Assets/
      * Image/
    * Config 
      * socketioConfig
   * index.js
   * package.json

**Comment by kannanhassouna** [comment]
- [ ] change the file structure each component should be in folder and that folder will contains : 
   - [ ] index.js
   - [ ] index.css
   - [ ] logic.js (optinal)
- [ ] change all files from jsx to js .

@Fatmasiam
